"""empty message

Revision ID: c0299f61e690
Revises: 
Create Date: 2021-11-16 22:30:09.270116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0299f61e690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operacao',
    sa.Column('id_operacao', sa.Integer(), nullable=False),
    sa.Column('tipo_operacao', sa.String(length=15), nullable=False),
    sa.Column('operacao_especifica', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id_operacao')
    )
    op.create_table('historico',
    sa.Column('id_historico', sa.Integer(), nullable=False),
    sa.Column('argumento', sa.String(length=15), nullable=False),
    sa.Column('resultado', sa.String(length=15), nullable=False),
    sa.Column('dt_registro', sa.DateTime(), nullable=False),
    sa.Column('id_operacao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_operacao'], ['operacao.id_operacao'], ),
    sa.PrimaryKeyConstraint('id_historico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico')
    op.drop_table('operacao')
    # ### end Alembic commands ###
